# Information
site_name: Kutilicious
site_author: Vladislav Kochetov
site_description: Lightweight library with a set of small Kotlin and Android extensions for a better development experience.

# Repository
repo_name: vladleesi/kutilicious
repo_url: https://github.com/vladleesi/kutilicious

# Configuration
theme:
  name: material
  features:
#    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vladleesi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vladkochetov
    - icon: fontawesome/brands/dev
      link: https://dev.to/vladleesi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/vladleesi

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/vladleesi"  target="_blank" rel="noopener">vladleesi</a>