plugins {
    id 'com.android.library'
}

android {
    namespace = 'dev.vladleesi.base'
    compileSdk = 37

    defaultConfig {
        minSdk = 23
        targetSdk = 37

        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    // Test
    testImplementation libs.unit.tests.junit
}
