name: GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/publish-docs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Generate site
        run: mkdocs gh-deploy --force --clean

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: site # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch