name: GitHub Pages

on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs/**'
      - '.github/workflows/publish-docs.yml'

permissions:
  contents: read
  deployments: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
